services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    healthcheck:
      test: [ "CMD", "/usr/bin/check-health" ]
      interval: 10s
      timeout: 3s
    volumes:
      - proxy-data:/data
      - proxy-letsencrypt:/etc/letsencrypt

  server:
    build:
      context: .
      target: final
    env_file: .env
    expose:
      - 8080

volumes:
  proxy-data:
  proxy-letsencrypt: